export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN'

