const cartTypes = {
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_DELETE_ITEM: 'CART_DELETE_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    CLEAR_CART: 'CLEAR_CART'
}

export default cartTypes

